# Generated by Django 3.2.4 on 2021-06-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
