# Generated by Django 3.2.4 on 2021-06-09 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oilapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_job_completer', to=settings.AUTH_USER_MODEL),
        ),
    ]
